name: exceptions_flutter
description: Repository which provides exceptions in a format
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0
